// gulpfile.js (ESM 버전)
// Node 14+ / gulp 4+ 호환

import { series, watch } from 'gulp';
import * as glob from 'glob';
import path from 'path';
import fs from 'fs';
import { fileURLToPath } from 'url';
import { deleteAsync } from 'del';

// ✅ ESM 환경에서 __dirname, __filename 대체
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// -----------------------------
// 설정
// -----------------------------
const PAGES_DIR = path.join(__dirname, 'pages');
const OUT_INDEX = path.join(PAGES_DIR, 'index.html');
const HTML_GLOB = path.join(PAGES_DIR, '*/*.html');

// -----------------------------
// 인덱스 파일 생성
// -----------------------------
function generateIndex(done) {
  const files = glob.sync(HTML_GLOB, { nodir: true });

  const groups = {};
  files.forEach((fullPath) => {
    const dir = path.dirname(fullPath);
    const category = path.basename(dir);
    const fileName = path.basename(fullPath);
    const relPath = './' + path.relative(PAGES_DIR, fullPath).replace(/\\/g, '/');
    if (!groups[category]) groups[category] = [];
    groups[category].push({ name: fileName, relPath });
  });

  const now = new Date();
  const header = `<!-- Generated by gulp buildIndex on ${now.toLocaleString()} -->\n`;
  let html = `<!doctype html>
<html lang="ko">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <title>STICH 파일 목록</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Noto Sans KR", "Apple SD Gothic Neo", sans-serif; padding: 24px; line-height:1.6; }
    h1 { margin-bottom: 8px; }
    .category { margin-bottom: 18px; }
    .category h2 { margin: 8px 0; font-size: 1.05rem; }
    ul { margin: 6px 0 12px 20px; }
    li {list-style: none;}
    a { text-decoration: none; }
    a:hover { text-decoration: underline; }
    .meta { color: #666; font-size: 0.9rem; margin-bottom: 18px; }
    .no-files { color: #b00; }
  </style>
</head>
<body>
  ${header}
  <h1>STICH HTML 파일 목록</h1>
  <div class="meta">생성일: ${now.toLocaleString()}</div>
`;

  const categoryNames = Object.keys(groups).sort();
  if (categoryNames.length === 0) {
    html += `<p class="no-files">검색된 파일이 없습니다. (경로: ${HTML_GLOB})</p>\n`;
  } else {
    categoryNames.forEach((cat) => {
      html += `<section class="category">\n  <h2>${cat} <small>(${groups[cat].length})</small></h2>\n  <ul>\n`;
      groups[cat]
        .sort((a, b) => a.name.localeCompare(b.name, 'ko'))
        .forEach((f) => {
          html += `    <li><a href="${f.relPath}" target="_blank" rel="noopener noreferrer">${f.name}</a></li>\n`;
        });
      html += `  </ul>\n</section>\n`;
    });
  }

  html += `
  <footer style="margin-top:30px;color:#888;font-size:0.9rem">
  </footer>
</body>
</html>`;

  fs.writeFileSync(OUT_INDEX, html, 'utf8');
  console.log(`✅ Index generated: ${OUT_INDEX} (${files.length} files)`);

  done();
}

// -----------------------------
// 기존 index.html 삭제
// -----------------------------
async function cleanIndex() {
  await deleteAsync([OUT_INDEX]);
  console.log('🧹 Old index.html deleted.');
}

// -----------------------------
// 변경 감지
// -----------------------------
export function watchIndex() {
  const watchGlob = path.join(PAGES_DIR, '**/*.html');
  const watcher = watch(watchGlob, { ignoreInitial: false }, generateIndex);
  console.log(`👀 Watching: ${watchGlob}`);
  return watcher;
}

// -----------------------------
// 기본 task
// -----------------------------
export const buildIndex = series(cleanIndex, generateIndex);
export default buildIndex;
